from app.models import db, Profile

def seed_profiles():
  profile1 = Profile(
  user_id =1,
  age = 24,
  location = 'Long Beach, California',
  lat = 33.85897723024835,
  lng = -118.08115190136616,
  about_me ="Costco food samples, manga, tea/coffee addict",
  goal = "Going to bed on time 😩. I get the most random, creative ideas at 11:30PM and the impulse to sacrifice sleep, in order to capture that idea in all of its glory...is a daily losing battle for me",
  talent = "8hr focus streaks when it comes to studying",
  my_traits ="creative, artsy, always confused, random, studious",
  needs = "good food",
  hobbies = "reading manga, coding, cafe hopping",
  moments = "When I fix a bug and when I put on a warm sweater fresh out of the dryer.",
  secrets = "I like doing random mundane things like peeling garlic",
  looking_for = "must have costco executive membership",
  user_audio = "https://res.cloudinary.com/mabmab/video/upload/v1640820480/okSign/example_audio_link_ubjhn1.mp3",
  gender_id =1,
  gender_preference_id=2,
  number_likes = 1,
  image_url1 = "https://res.cloudinary.com/mabmab/image/upload/v1639292458/okSign/kelsey1_yut7zy.png",
  image_url2 = "https://res.cloudinary.com/mabmab/image/upload/v1639294329/okSign/IMG_1193_amp2ic.jpg",
  image_url3 = "https://res.cloudinary.com/mabmab/image/upload/v1639294327/okSign/IMG_1196_rntazj.jpg",
  image_url4 = "https://res.cloudinary.com/mabmab/image/upload/v1639293141/okSign/Screen_Shot_2021-12-11_at_11.11.52_PM_kdphkm.png",
  image_url5 = "https://res.cloudinary.com/mabmab/image/upload/v1639294470/okSign/IMG_1192_dtdyvh.jpg",
  image_url6 = "https://res.cloudinary.com/mabmab/image/upload/v1639294665/okSign/Screen_Shot_2021-12-11_at_11.16.59_PM_mez2fg.png",
  orientation_id =1,
  partner_id =1,
  pronouns = "she/her",
  height = 165,
  education = "Stanford University",
  occupation = "Student",
  horoscope_id =11,
  smoking_id = 4,
  drinking_id = 2,
  children_id =3,
  pet_id =1,
  politic_id =2,
  religion_id = 8,
  )

  profile2 = Profile(
  user_id =2,
  age = 28,
  location = 'Tokyo, Japan',
  lat = 35.66386037006631,
  lng = 139.71280545767016,
  about_me ="Ex-salaryman and maybe soon to be your ex. The corporate life was draining so I quit and became a sorcerer again. Hopefully, you won't be draining too.",
  goal = "to mentor Yuji well and destroy curses.",
  talent = "can perfectly divide anything into a 7:3 ratio point",
  my_traits ="serious and always tired",
  needs = "I just want to retire and read a good book at a beach in Malaysia.",
  hobbies = "reading at cafes",
  moments = "geting off work",
  secrets = "I hate working from 9 to 5",
  looking_for = "A decent person. I tend to be blunt so I need someone who can handle that. I promise to always be honest and I hope for you to do the same.",
  user_audio = "https://res.cloudinary.com/mabmab/video/upload/v1639359984/okSign/nanami_audio_tq9fb3.mp3",
  gender_id =2,
  gender_preference_id=1,
  number_likes = 2,
  image_url1 = "https://res.cloudinary.com/mabmab/image/upload/v1639360501/okSign/Screen_Shot_2021-12-12_at_5.54.56_PM_x2tg82.png",
  image_url2 = "https://res.cloudinary.com/mabmab/image/upload/v1639360649/okSign/Screen_Shot_2021-12-12_at_5.57.22_PM_klubft.png",
  image_url3 = "https://res.cloudinary.com/mabmab/image/upload/v1639360793/okSign/Screen_Shot_2021-12-12_at_5.59.47_PM_kdl0py.png",
  image_url4 = "https://res.cloudinary.com/mabmab/image/upload/v1639360604/okSign/Screen_Shot_2021-12-12_at_5.56.35_PM_tkqbgd.png",
  image_url5 = "https://res.cloudinary.com/mabmab/image/upload/v1639361013/okSign/Screen_Shot_2021-12-12_at_6.03.25_PM_x0xfzv.png",
  image_url6 = "https://res.cloudinary.com/mabmab/image/upload/v1639360809/okSign/Screen_Shot_2021-12-12_at_6.00.02_PM_rqfsy2.png",
  orientation_id =1,
  partner_id =1,
  pronouns ='He/Him',
  height = 184,
  education = "Jujutsu Tech",
  occupation ="Jujutsu sorcerer",
  religion_id = 10,
  horoscope_id =4,
  smoking_id = 4,
  drinking_id = 3,
  children_id =3,
  pet_id =1,
  politic_id =4
  )

  profile3 = Profile(
  user_id =3,
  age = 200,
  location = 'Xiamen, China',
  lat = 24.50730758155893,
  lng = 118.06432149234764,
  about_me ="I'm often told that I'm blunt but I think life's best policy is to be straightforward. If you're dishonest, I'm merciless. I have no respect for anyone unless they're stronger than me.",
  goal = "to become king",
  talent = "I can fly",
  my_traits ="brutal, impulsive, violent, and sometimes short tempered",
  needs = "to become king",
  hobbies = "picking fights",
  moments = "when I win a fight",
  secrets = "...what's a secret if known?",
  looking_for = "Someone that won't back down from a fight. ",
  user_audio = "https://res.cloudinary.com/mabmab/video/upload/v1639292032/okSign/New_Coronavirus_Laws_Funny_vu9ais.mp3",
  gender_id =2,
  gender_preference_id=1,
  number_likes = 2,
  image_url1 = "https://res.cloudinary.com/mabmab/image/upload/v1640729284/okSign/Screen_Shot_2021-12-28_at_2.07.58_PM_yijcc8.png",
  image_url2 = "https://res.cloudinary.com/mabmab/image/upload/v1640729417/okSign/Screen_Shot_2021-12-28_at_2.10.11_PM_bh8vmx.png",
  image_url3 = "https://res.cloudinary.com/mabmab/image/upload/v1640728850/okSign/Screen_Shot_2021-12-28_at_2.00.45_PM_rpekts.png",
  image_url4 = "https://res.cloudinary.com/mabmab/image/upload/v1640728676/okSign/Screen_Shot_2021-12-28_at_1.57.45_PM_nqkpe0.png",
  image_url5 = "https://res.cloudinary.com/mabmab/image/upload/v1640729581/okSign/Screen_Shot_2021-12-28_at_2.12.54_PM_czl9zl.png",
  image_url6 = "https://res.cloudinary.com/mabmab/image/upload/v1639454473/okSign/Screen_Shot_2021-12-13_at_8.01.05_PM_lmvdnf.png",
  orientation_id =1,
  partner_id =3,
  pronouns ='He/Him',
  height = 185,
  education = "n/a",
  occupation ="Sexta Espada",
  religion_id = 10,
  horoscope_id =5,
  smoking_id = 1,
  drinking_id = 2,
  children_id =3,
  pet_id =1,
  politic_id =4
  )

  profile4 = Profile(
  user_id =4,
  age = 85,
  location = 'Ho Chi Minh City, Vietnam',
  lat = 11.44400353481068,
  lng = 106.74188131038807,
  about_me ="I don't have the patience to tolerate someone who is inconsistent. If that sounds like you, please exit out my profile. I'm also a vampire but I can tolerate day to day human activies.",
  goal = "to be a great vampire knight and to protect my loved ones",
  talent = "I can eat garlic and stay out in the sun...",
  my_traits ="composed, quiet, cold",
  needs = "alone time... I need time to collect my thoughts and just reflect",
  hobbies = "developing my skills in combat",
  moments = "spending time with family",
  secrets = "I generally come across as a cold-hearted person but I'm actually pretty sweet.",
  looking_for = "someone who is honest, kind, and warm",
  user_audio = "https://res.cloudinary.com/mabmab/video/upload/v1639292032/okSign/New_Coronavirus_Laws_Funny_vu9ais.mp3",
  gender_id =2,
  gender_preference_id=1,
  number_likes = 2,
  image_url1 = "https://res.cloudinary.com/mabmab/image/upload/v1640730916/okSign/Screen_Shot_2021-12-28_at_2.35.10_PM_osy5nj.png",
  image_url2 = "https://res.cloudinary.com/mabmab/image/upload/v1640730241/okSign/Screen_Shot_2021-12-28_at_2.23.55_PM_clalh9.png",
  image_url3 = "https://res.cloudinary.com/mabmab/image/upload/v1640730348/okSign/Screen_Shot_2021-12-28_at_2.25.43_PM_j8fuog.png",
  image_url4 = "https://res.cloudinary.com/mabmab/image/upload/v1640730004/okSign/Screen_Shot_2021-12-28_at_2.19.57_PM_unymkf.png",
  image_url5 = "https://res.cloudinary.com/mabmab/image/upload/v1640730304/okSign/Screen_Shot_2021-12-28_at_2.24.57_PM_cjfymg.png",
  image_url6 = "https://res.cloudinary.com/mabmab/image/upload/v1640730069/okSign/Screen_Shot_2021-12-28_at_2.21.02_PM_dc20wi.png",
  orientation_id =1,
  partner_id =3,
  pronouns ='He/Him',
  height = 185,
  education = "n/a",
  occupation ="vampire knight",
  religion_id = 10,
  horoscope_id =8,
  smoking_id = 4,
  drinking_id = 2,
  children_id =3,
  pet_id =1,
  politic_id =4
  )


  profile5 = Profile(
  user_id =5,
  age = 25,
  location = 'Tokyo, Japan',
  lat = 39.94924892692659,
  lng = 140.89645614613545,
  about_me ="I am a detective. I solve mysteries that are too difficult for the police. I am confident that I can figure out what we're going to eat for dinner. No more wasting an hour trying to decide.",
  goal = "To capture the criminal behind Japan's latest murders",
  talent = "I can solve mysteries that the police can't handle",
  my_traits ="sharp, intelligent, and mysterious",
  needs = "An endless supply of sweets",
  hobbies = "solving crimes",
  moments = "When I'm able to connect all the dots togethers for a murder case",
  secrets = "I can't live without cake, chocolate, and tea.",
  looking_for = "Someone who is a great problem solver or someone who is a pastry chef",
  user_audio = "https://res.cloudinary.com/mabmab/video/upload/v1640820480/okSign/example_audio_link_ubjhn1.mp3",
  gender_id =2,
  gender_preference_id=1,
  number_likes = 2,
  image_url1 = "https://res.cloudinary.com/mabmab/image/upload/v1643058500/okSign/Screen_Shot_2022-01-24_at_1.08.16_PM_m8dqch.png",
  image_url2 = "https://res.cloudinary.com/mabmab/image/upload/v1643058595/okSign/Screen_Shot_2022-01-24_at_1.09.52_PM_kay0gn.png",
  image_url3 = "https://res.cloudinary.com/mabmab/image/upload/v1643058437/okSign/Screen_Shot_2022-01-24_at_1.07.13_PM_pvqmqf.png",
  image_url4 = "https://res.cloudinary.com/mabmab/image/upload/v1643058371/okSign/Screen_Shot_2022-01-24_at_1.06.06_PM_fkltwj.png",
  image_url5 = "https://res.cloudinary.com/mabmab/image/upload/v1643058574/okSign/Screen_Shot_2022-01-24_at_1.09.28_PM_iuazpc.png",
  image_url6 = "https://res.cloudinary.com/mabmab/image/upload/v1643058393/okSign/Screen_Shot_2022-01-24_at_1.06.29_PM_n6d0kj.png",
  orientation_id =1,
  partner_id =3,
  pronouns ='He/Him',
  height = 178,
  education = "n/a",
  occupation ="Detective",
  religion_id = 10,
  horoscope_id =8,
  smoking_id = 4,
  drinking_id = 2,
  children_id =3,
  pet_id =1,
  politic_id =4
  )

  profile6 = Profile(
  user_id =6,
  age = 30,
  location = 'Tokyo, Japan',
  lat = 43.39459127248536,
  lng = 142.610322591344,
  about_me ="I tend to look half-asleep but don't worry, you have my full attention.",
  goal = "To continue to raise virtuous ninjas",
  talent = "I can pretty much do everything with just one eye",
  my_traits ="calm, sharp, helpful",
  needs = "Preferably someone who is also laidback. If not, someone who is well organized and push me forward to get stuff done. I can be a little lazy and not very punctual with time.",
  hobbies = "I really enjoy passing the time by reading.",
  moments = "When my students are able to pick up new skills :)! ",
  secrets = "All of my students want to know how my face looks like...for the right one...I'll reveal it.",
  looking_for = "As stated before, someone laidback or very organized!",
  user_audio = "https://res.cloudinary.com/mabmab/video/upload/v1640820480/okSign/example_audio_link_ubjhn1.mp3",
  gender_id =2,
  gender_preference_id=1,
  number_likes = 2,
  image_url1 = "https://res.cloudinary.com/mabmab/image/upload/v1643059622/okSign/Screen_Shot_2022-01-24_at_1.26.54_PM_jfy8eb.png",
  image_url2 = "https://res.cloudinary.com/mabmab/image/upload/v1643059490/okSign/Screen_Shot_2022-01-24_at_1.24.43_PM_e1ivxx.png",
  image_url3 = "https://res.cloudinary.com/mabmab/image/upload/v1643059732/okSign/Screen_Shot_2022-01-24_at_1.28.46_PM_ooirrq.png",
  image_url4 = "https://res.cloudinary.com/mabmab/image/upload/v1643059868/okSign/Screen_Shot_2022-01-24_at_1.31.05_PM_ethc8a.png",
  image_url5 = "https://res.cloudinary.com/mabmab/image/upload/v1643059561/okSign/Screen_Shot_2022-01-24_at_1.25.55_PM_vbuf5m.png",
  image_url6 = "https://res.cloudinary.com/mabmab/image/upload/v1643059707/okSign/Screen_Shot_2022-01-24_at_1.28.23_PM_tk7ita.png",
  orientation_id =1,
  partner_id =3,
  pronouns ='He/Him',
  height = 181,
  education = "Konoha Gakure",
  occupation ="Teacher",
  religion_id = 10,
  horoscope_id =5,
  smoking_id = 4,
  drinking_id = 2,
  children_id =3,
  pet_id =1,
  politic_id =4
  )

  # profile4 = Profile(
  # user_id =4,
  # age = 85,
  # location = '',
  # lat = ,
  # lng = ,
  # about_me ="",
  # goal = "",
  # talent = "",
  # my_traits ="",
  # needs = "",
  # hobbies = "",
  # moments = "",
  # secrets = "",
  # looking_for = "",
  # user_audio = "https://res.cloudinary.com/mabmab/video/upload/v1640820480/okSign/example_audio_link_ubjhn1.mp3",
  # gender_id =2,
  # gender_preference_id=1,
  # number_likes = 2,
  # image_url1 = "",
  # image_url2 = "",
  # image_url3 = "",
  # image_url4 = "",
  # image_url5 = "",
  # image_url6 = "",
  # orientation_id =1,
  # partner_id =3,
  # pronouns ='',
  # height = 185,
  # education = "",
  # occupation ="",
  # religion_id = 10,
  # horoscope_id =8,
  # smoking_id = 4,
  # drinking_id = 2,
  # children_id =3,
  # pet_id =1,
  # politic_id =4
  # )


  db.session.add(profile1)
  db.session.add(profile2)
  db.session.add(profile3)
  db.session.add(profile4)
  db.session.add(profile5)
  db.session.add(profile6)

  db.session.commit()

def undo_profiles():
    db.session.execute('TRUNCATE profiles RESTART IDENTITY CASCADE;')
    db.session.commit()
