"""empty message

Revision ID: 04bc3035fdd4
Revises: 66b1222ff4b0
Create Date: 2021-12-15 22:06:09.705528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04bc3035fdd4'
down_revision = '66b1222ff4b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('profiles_gender_preference_id_fkey', 'profiles', type_='foreignkey')
    op.drop_column('profiles', 'gender_preference_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('gender_preference_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('profiles_gender_preference_id_fkey', 'profiles', 'genders', ['gender_preference_id'], ['id'])
    # ### end Alembic commands ###
