"""empty message

Revision ID: 0d1d009fb49c
Revises: 65c0d77b163c
Create Date: 2021-12-15 21:17:44.016344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d1d009fb49c'
down_revision = '65c0d77b163c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genders', sa.Column('name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('genders', 'name')
    # ### end Alembic commands ###
