"""empty message

Revision ID: 0e8bca0a1c5b
Revises: d5ef0f9292b2
Create Date: 2021-12-15 21:08:25.415510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e8bca0a1c5b'
down_revision = 'd5ef0f9292b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('profiles_politic_id_fkey', 'profiles', type_='foreignkey')
    op.drop_constraint('profiles_religion_id_fkey', 'profiles', type_='foreignkey')
    op.drop_constraint('profiles_pet_id_fkey', 'profiles', type_='foreignkey')
    op.drop_column('profiles', 'pet_id')
    op.drop_column('profiles', 'religion_id')
    op.drop_column('profiles', 'politic_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('politic_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('religion_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('pet_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('profiles_pet_id_fkey', 'profiles', 'pets', ['pet_id'], ['id'])
    op.create_foreign_key('profiles_religion_id_fkey', 'profiles', 'religions', ['religion_id'], ['id'])
    op.create_foreign_key('profiles_politic_id_fkey', 'profiles', 'politics', ['politic_id'], ['id'])
    # ### end Alembic commands ###
