"""empty message

Revision ID: 1a8d22df58ed
Revises: 04bc3035fdd4
Create Date: 2021-12-15 22:08:54.126589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a8d22df58ed'
down_revision = '04bc3035fdd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('gender_preference_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'profiles', 'genders', ['gender_preference_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_column('profiles', 'gender_preference_id')
    # ### end Alembic commands ###
