"""empty message

Revision ID: 1bc2ac0bad22
Revises: 8999cc76e81f
Create Date: 2021-12-12 20:21:41.222964

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1bc2ac0bad22'
down_revision = '8999cc76e81f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('conversations_user_id_two_fkey', 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'date')
    op.drop_column('conversations', 'created_at')
    op.drop_column('conversations', 'user_id_two')
    op.drop_column('conversations', 'updated_at')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'email')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.add_column('conversations', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('conversations', sa.Column('user_id_two', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('conversations', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('conversations', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    op.create_foreign_key('conversations_user_id_two_fkey', 'conversations', 'users', ['user_id_two'], ['id'])
    # ### end Alembic commands ###
