"""empty message

Revision ID: af98096dc98a
Revises: f466b8529b54
Create Date: 2021-12-12 20:37:23.001393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af98096dc98a'
down_revision = 'f466b8529b54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('location', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('profiles', sa.Column('lng', sa.Float(), nullable=True))
    op.add_column('profiles', sa.Column('about_me', sa.String(length=255), nullable=True))
    op.add_column('profiles', sa.Column('goal', sa.String(length=255), nullable=True))
    op.add_column('profiles', sa.Column('talent', sa.String(length=255), nullable=True))
    op.add_column('profiles', sa.Column('my_traits', sa.String(length=255), nullable=True))
    op.add_column('profiles', sa.Column('needs', sa.String(length=255), nullable=True))
    op.add_column('profiles', sa.Column('hobbies', sa.String(length=255), nullable=True))
    op.add_column('profiles', sa.Column('moments', sa.String(length=255), nullable=True))
    op.add_column('profiles', sa.Column('secrets', sa.String(length=255), nullable=True))
    op.add_column('profiles', sa.Column('looking_for', sa.String(length=255), nullable=True))
    op.add_column('profiles', sa.Column('user_audio', sa.String(length=255), nullable=True))
    op.add_column('profiles', sa.Column('gender_id', sa.Integer(), nullable=True))
    op.add_column('profiles', sa.Column('number_likes', sa.Integer(), nullable=True))
    op.add_column('profiles', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('orientation_id', sa.Integer(), nullable=True))
    op.add_column('profiles', sa.Column('relationship_id', sa.Integer(), nullable=True))
    op.add_column('profiles', sa.Column('pronouns', sa.String(length=255), nullable=True))
    op.add_column('profiles', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('profiles', sa.Column('education', sa.String(length=255), nullable=True))
    op.add_column('profiles', sa.Column('occupation', sa.String(length=255), nullable=True))
    op.add_column('profiles', sa.Column('horoscope_id', sa.Integer(), nullable=True))
    op.add_column('profiles', sa.Column('smoking', sa.Boolean(), nullable=True))
    op.add_column('profiles', sa.Column('drinking', sa.Boolean(), nullable=True))
    op.add_column('profiles', sa.Column('children_id', sa.Integer(), nullable=True))
    op.add_column('profiles', sa.Column('pet_id', sa.Integer(), nullable=True))
    op.add_column('profiles', sa.Column('politic_id', sa.Integer(), nullable=True))
    op.add_column('profiles', sa.Column('religion_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'profiles', 'pets', ['pet_id'], ['id'])
    op.create_foreign_key(None, 'profiles', 'horoscopes', ['horoscope_id'], ['id'])
    op.create_foreign_key(None, 'profiles', 'religions', ['religion_id'], ['id'])
    op.create_foreign_key(None, 'profiles', 'children', ['children_id'], ['id'])
    op.create_foreign_key(None, 'profiles', 'politics', ['politic_id'], ['id'])
    op.create_foreign_key(None, 'profiles', 'genders', ['gender_id'], ['id'])
    op.create_foreign_key(None, 'profiles', 'relationships', ['relationship_id'], ['id'])
    op.create_foreign_key(None, 'profiles', 'orientations', ['orientation_id'], ['id'])
    op.add_column('relationships', sa.Column('type', sa.String(length=255), nullable=True))
    op.add_column('relationships', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('relationships', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relationships', 'updated_at')
    op.drop_column('relationships', 'created_at')
    op.drop_column('relationships', 'type')
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_column('profiles', 'religion_id')
    op.drop_column('profiles', 'politic_id')
    op.drop_column('profiles', 'pet_id')
    op.drop_column('profiles', 'children_id')
    op.drop_column('profiles', 'drinking')
    op.drop_column('profiles', 'smoking')
    op.drop_column('profiles', 'horoscope_id')
    op.drop_column('profiles', 'occupation')
    op.drop_column('profiles', 'education')
    op.drop_column('profiles', 'height')
    op.drop_column('profiles', 'pronouns')
    op.drop_column('profiles', 'relationship_id')
    op.drop_column('profiles', 'orientation_id')
    op.drop_column('profiles', 'image_url')
    op.drop_column('profiles', 'number_likes')
    op.drop_column('profiles', 'gender_id')
    op.drop_column('profiles', 'user_audio')
    op.drop_column('profiles', 'looking_for')
    op.drop_column('profiles', 'secrets')
    op.drop_column('profiles', 'moments')
    op.drop_column('profiles', 'hobbies')
    op.drop_column('profiles', 'needs')
    op.drop_column('profiles', 'my_traits')
    op.drop_column('profiles', 'talent')
    op.drop_column('profiles', 'goal')
    op.drop_column('profiles', 'about_me')
    op.drop_column('profiles', 'lng')
    op.drop_column('profiles', 'lat')
    op.drop_column('profiles', 'location')
    # ### end Alembic commands ###
