"""empty message

Revision ID: 6ac811766b5d
Revises: 1bcd9fdea58b
Create Date: 2021-12-12 19:21:05.017521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ac811766b5d'
down_revision = '1bcd9fdea58b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('user_id_two', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'conversations', 'users', ['user_id_two'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'user_id_two')
    # ### end Alembic commands ###
