"""empty message

Revision ID: 8debe38f7b33
Revises: 72aca9ab0be6
Create Date: 2021-12-12 20:45:30.974148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8debe38f7b33'
down_revision = '72aca9ab0be6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relationships', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relationships', 'updated_at')
    # ### end Alembic commands ###
