"""empty message

Revision ID: 50b0d8b3629d
Revises: 0527631380e5
Create Date: 2021-12-12 20:50:28.786181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50b0d8b3629d'
down_revision = '0527631380e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('horoscope_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'profiles', 'horoscopes', ['horoscope_id'], ['id'])
    op.add_column('relationships', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relationships', 'updated_at')
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_column('profiles', 'horoscope_id')
    # ### end Alembic commands ###
