"""empty message

Revision ID: 3d36ae4cf29d
Revises: ffdc0a98111c
Create Date: 2021-12-12 18:44:44.434816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d36ae4cf29d'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('children',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('option', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('horoscopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sign', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('match', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orientations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('option', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('politics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('belief', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('religions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('belief', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id_one', sa.Integer(), nullable=True),
    sa.Column('user_id_two', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id_one'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id_two'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question1', sa.String(), nullable=True),
    sa.Column('must_answer1', sa.String(), nullable=True),
    sa.Column('question2', sa.String(), nullable=True),
    sa.Column('must_answer2', sa.String(), nullable=True),
    sa.Column('question3', sa.String(), nullable=True),
    sa.Column('must_answer3', sa.String(), nullable=True),
    sa.Column('question4', sa.String(), nullable=True),
    sa.Column('must_answer4', sa.String(), nullable=True),
    sa.Column('question5', sa.String(), nullable=True),
    sa.Column('must_answer5', sa.String(), nullable=True),
    sa.Column('question6', sa.String(), nullable=True),
    sa.Column('must_answer6', sa.String(), nullable=True),
    sa.Column('question7', sa.String(), nullable=True),
    sa.Column('must_answer7', sa.String(), nullable=True),
    sa.Column('question8', sa.String(), nullable=True),
    sa.Column('must_answer8', sa.String(), nullable=True),
    sa.Column('question9', sa.String(), nullable=True),
    sa.Column('must_answer9', sa.String(), nullable=True),
    sa.Column('question10', sa.String(), nullable=True),
    sa.Column('must_answer10', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userProfiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('about_me', sa.String(length=255), nullable=True),
    sa.Column('goal', sa.String(length=255), nullable=True),
    sa.Column('talent', sa.String(length=255), nullable=True),
    sa.Column('my_traits', sa.String(length=255), nullable=True),
    sa.Column('needs', sa.String(length=255), nullable=True),
    sa.Column('hobbies', sa.String(length=255), nullable=True),
    sa.Column('moments', sa.String(length=255), nullable=True),
    sa.Column('secrets', sa.String(length=255), nullable=True),
    sa.Column('looking_for', sa.String(length=255), nullable=True),
    sa.Column('user_audio', sa.String(length=255), nullable=True),
    sa.Column('gender_id', sa.Integer(), nullable=True),
    sa.Column('number_likes', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('orientation_id', sa.Integer(), nullable=True),
    sa.Column('relationship_id', sa.Integer(), nullable=True),
    sa.Column('pronouns', sa.String(length=255), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('education', sa.String(length=255), nullable=True),
    sa.Column('occupation', sa.String(length=255), nullable=True),
    sa.Column('horoscope_id', sa.Integer(), nullable=True),
    sa.Column('smoking', sa.Boolean(), nullable=True),
    sa.Column('drinking', sa.Boolean(), nullable=True),
    sa.Column('children_id', sa.Integer(), nullable=True),
    sa.Column('pet_id', sa.Integer(), nullable=True),
    sa.Column('politic_id', sa.Integer(), nullable=True),
    sa.Column('religion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['children_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['gender_id'], ['genders.id'], ),
    sa.ForeignKeyConstraint(['horoscope_id'], ['horoscopes.id'], ),
    sa.ForeignKeyConstraint(['orientation_id'], ['orientations.id'], ),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.ForeignKeyConstraint(['politic_id'], ['politics.id'], ),
    sa.ForeignKeyConstraint(['relationship_id'], ['relationships.id'], ),
    sa.ForeignKeyConstraint(['religion_id'], ['religions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('from_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('first_name', sa.String(length=30), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=30), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_table('messages')
    op.drop_table('userProfiles')
    op.drop_table('questions')
    op.drop_table('conversations')
    op.drop_table('religions')
    op.drop_table('relationships')
    op.drop_table('politics')
    op.drop_table('pets')
    op.drop_table('orientations')
    op.drop_table('horoscopes')
    op.drop_table('genders')
    op.drop_table('children')
    # ### end Alembic commands ###
