"""empty message

Revision ID: a18ced3eaf09
Revises: 8debe38f7b33
Create Date: 2021-12-12 20:46:40.141740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a18ced3eaf09'
down_revision = '8debe38f7b33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relationships', sa.Column('title', sa.String(length=255), nullable=True))
    op.drop_column('relationships', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relationships', sa.Column('type', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('relationships', 'title')
    # ### end Alembic commands ###
