"""empty message

Revision ID: 4ba3c212c9ec
Revises: 3d36ae4cf29d
Create Date: 2021-12-12 18:57:13.038292

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4ba3c212c9ec'
down_revision = '3d36ae4cf29d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('userProfiles_user_id_fkey', 'userProfiles', type_='foreignkey')
    op.drop_column('userProfiles', 'hobbies')
    op.drop_column('userProfiles', 'moments')
    op.drop_column('userProfiles', 'lat')
    op.drop_column('userProfiles', 'needs')
    op.drop_column('userProfiles', 'goal')
    op.drop_column('userProfiles', 'user_id')
    op.drop_column('userProfiles', 'about_me')
    op.drop_column('userProfiles', 'secrets')
    op.drop_column('userProfiles', 'my_traits')
    op.drop_column('userProfiles', 'lng')
    op.drop_column('userProfiles', 'location')
    op.drop_column('userProfiles', 'looking_for')
    op.drop_column('userProfiles', 'talent')
    op.drop_column('userProfiles', 'age')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userProfiles', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('userProfiles', sa.Column('talent', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('userProfiles', sa.Column('looking_for', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('userProfiles', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('userProfiles', sa.Column('lng', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('userProfiles', sa.Column('my_traits', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('userProfiles', sa.Column('secrets', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('userProfiles', sa.Column('about_me', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('userProfiles', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('userProfiles', sa.Column('goal', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('userProfiles', sa.Column('needs', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('userProfiles', sa.Column('lat', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('userProfiles', sa.Column('moments', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('userProfiles', sa.Column('hobbies', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_foreign_key('userProfiles_user_id_fkey', 'userProfiles', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
