"""empty message

Revision ID: 92237953f6e9
Revises: 69081f5ad2e9
Create Date: 2021-12-12 20:17:54.697692

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '92237953f6e9'
down_revision = '69081f5ad2e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('conversations_user_id_one_fkey', 'conversations', type_='foreignkey')
    op.drop_constraint('conversations_user_id_two_fkey', 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'created_at')
    op.drop_column('conversations', 'user_id_two')
    op.drop_column('conversations', 'updated_at')
    op.drop_column('conversations', 'user_id_one')
    op.drop_column('conversations', 'date')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'username')
    op.drop_column('users', 'email')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.add_column('conversations', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('conversations', sa.Column('user_id_one', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('conversations', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('conversations', sa.Column('user_id_two', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('conversations', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.create_foreign_key('conversations_user_id_two_fkey', 'conversations', 'users', ['user_id_two'], ['id'])
    op.create_foreign_key('conversations_user_id_one_fkey', 'conversations', 'users', ['user_id_one'], ['id'])
    # ### end Alembic commands ###
