"""empty message

Revision ID: 0527631380e5
Revises: a18ced3eaf09
Create Date: 2021-12-12 20:50:13.775910

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0527631380e5'
down_revision = 'a18ced3eaf09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('profiles_horoscope_id_fkey', 'profiles', type_='foreignkey')
    op.drop_column('profiles', 'horoscope_id')
    op.drop_column('relationships', 'updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relationships', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('horoscope_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('profiles_horoscope_id_fkey', 'profiles', 'horoscopes', ['horoscope_id'], ['id'])
    # ### end Alembic commands ###
