"""empty message

Revision ID: 8e3e8a85c8ae
Revises: af98096dc98a
Create Date: 2021-12-12 20:39:37.182027

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8e3e8a85c8ae'
down_revision = 'af98096dc98a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('profiles_relationship_id_fkey', 'profiles', type_='foreignkey')
    op.drop_column('profiles', 'relationship_id')
    op.drop_column('relationships', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relationships', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('relationship_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('profiles_relationship_id_fkey', 'profiles', 'relationships', ['relationship_id'], ['id'])
    # ### end Alembic commands ###
