"""empty message

Revision ID: 9cad700b53bd
Revises: febfbe1e5c8f
Create Date: 2021-12-12 20:35:46.837739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cad700b53bd'
down_revision = 'febfbe1e5c8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('occupation', sa.String(length=255), nullable=True))
    op.add_column('profiles', sa.Column('horoscope_id', sa.Integer(), nullable=True))
    op.add_column('profiles', sa.Column('smoking', sa.Boolean(), nullable=True))
    op.add_column('profiles', sa.Column('drinking', sa.Boolean(), nullable=True))
    op.add_column('profiles', sa.Column('children_id', sa.Integer(), nullable=True))
    op.add_column('profiles', sa.Column('pet_id', sa.Integer(), nullable=True))
    op.add_column('profiles', sa.Column('politic_id', sa.Integer(), nullable=True))
    op.add_column('profiles', sa.Column('religion_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'profiles', 'horoscopes', ['horoscope_id'], ['id'])
    op.create_foreign_key(None, 'profiles', 'religions', ['religion_id'], ['id'])
    op.create_foreign_key(None, 'profiles', 'pets', ['pet_id'], ['id'])
    op.create_foreign_key(None, 'profiles', 'children', ['children_id'], ['id'])
    op.create_foreign_key(None, 'profiles', 'politics', ['politic_id'], ['id'])
    op.add_column('relationships', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relationships', 'updated_at')
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_column('profiles', 'religion_id')
    op.drop_column('profiles', 'politic_id')
    op.drop_column('profiles', 'pet_id')
    op.drop_column('profiles', 'children_id')
    op.drop_column('profiles', 'drinking')
    op.drop_column('profiles', 'smoking')
    op.drop_column('profiles', 'horoscope_id')
    op.drop_column('profiles', 'occupation')
    # ### end Alembic commands ###
