"""empty message

Revision ID: b2d352f6543d
Revises: 4ba3c212c9ec
Create Date: 2021-12-12 19:01:47.776717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2d352f6543d'
down_revision = '4ba3c212c9ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userProfiles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userProfiles',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"userProfiles_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('user_audio', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('gender_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('number_likes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('orientation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('relationship_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pronouns', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('education', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('occupation', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('horoscope_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('smoking', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('drinking', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('children_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pet_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('politic_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('religion_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['children_id'], ['children.id'], name='userProfiles_children_id_fkey'),
    sa.ForeignKeyConstraint(['gender_id'], ['genders.id'], name='userProfiles_gender_id_fkey'),
    sa.ForeignKeyConstraint(['horoscope_id'], ['horoscopes.id'], name='userProfiles_horoscope_id_fkey'),
    sa.ForeignKeyConstraint(['orientation_id'], ['orientations.id'], name='userProfiles_orientation_id_fkey'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name='userProfiles_pet_id_fkey'),
    sa.ForeignKeyConstraint(['politic_id'], ['politics.id'], name='userProfiles_politic_id_fkey'),
    sa.ForeignKeyConstraint(['relationship_id'], ['relationships.id'], name='userProfiles_relationship_id_fkey'),
    sa.ForeignKeyConstraint(['religion_id'], ['religions.id'], name='userProfiles_religion_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='userProfiles_pkey')
    )
    # ### end Alembic commands ###
