"""empty message

Revision ID: 2291a0ff80c4
Revises: 82f9f9506d06
Create Date: 2021-12-15 23:48:08.699424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2291a0ff80c4'
down_revision = '82f9f9506d06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drinkings', sa.Column('name', sa.String(length=255), nullable=True))
    op.drop_column('drinkings', 'option')
    op.add_column('smokings', sa.Column('name', sa.String(length=255), nullable=True))
    op.drop_column('smokings', 'option')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('smokings', sa.Column('option', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('smokings', 'name')
    op.add_column('drinkings', sa.Column('option', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('drinkings', 'name')
    # ### end Alembic commands ###
