"""empty message

Revision ID: 3bbd161a10c7
Revises: 857a650a448f
Create Date: 2021-12-12 21:00:26.691063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bbd161a10c7'
down_revision = '857a650a448f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('profiles_relationship_id_fkey', 'profiles', type_='foreignkey')
    op.drop_column('profiles', 'relationship_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('relationship_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('profiles_relationship_id_fkey', 'profiles', 'partners', ['relationship_id'], ['id'])
    # ### end Alembic commands ###
