"""empty message

Revision ID: 5516cfe71b18
Revises: f699a6644346
Create Date: 2021-12-12 21:47:29.491904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5516cfe71b18'
down_revision = 'f699a6644346'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'date')
    # ### end Alembic commands ###
