"""empty message

Revision ID: 605ca2a91835
Revises: 0e8bca0a1c5b
Create Date: 2021-12-15 21:08:49.883198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '605ca2a91835'
down_revision = '0e8bca0a1c5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('pet_id', sa.Integer(), nullable=True))
    op.add_column('profiles', sa.Column('politic_id', sa.Integer(), nullable=True))
    op.add_column('profiles', sa.Column('religion_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'profiles', 'religions', ['religion_id'], ['id'])
    op.create_foreign_key(None, 'profiles', 'pets', ['pet_id'], ['id'])
    op.create_foreign_key(None, 'profiles', 'politics', ['politic_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_column('profiles', 'religion_id')
    op.drop_column('profiles', 'politic_id')
    op.drop_column('profiles', 'pet_id')
    # ### end Alembic commands ###
