"""empty message

Revision ID: 61075fb7b68b
Revises: f03090a07695
Create Date: 2021-12-12 21:39:44.806153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61075fb7b68b'
down_revision = 'f03090a07695'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('question7', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('must_answer7', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('question8', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('must_answer8', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('question9', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('must_answer9', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('question10', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('must_answer10', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'must_answer10')
    op.drop_column('questions', 'question10')
    op.drop_column('questions', 'must_answer9')
    op.drop_column('questions', 'question9')
    op.drop_column('questions', 'must_answer8')
    op.drop_column('questions', 'question8')
    op.drop_column('questions', 'must_answer7')
    op.drop_column('questions', 'question7')
    # ### end Alembic commands ###
