"""empty message

Revision ID: 6da2c0407299
Revises: 97e05f554f72
Create Date: 2021-12-12 21:44:52.812156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6da2c0407299'
down_revision = '97e05f554f72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'date')
    # ### end Alembic commands ###
