"""empty message

Revision ID: 6e7ef659887f
Revises: 5f07b843b9d9
Create Date: 2021-12-12 21:04:16.084270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e7ef659887f'
down_revision = '5f07b843b9d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('children', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('children', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('children', 'updated_at')
    op.drop_column('children', 'created_at')
    # ### end Alembic commands ###
