"""empty message

Revision ID: 82f9f9506d06
Revises: ff2e3d7b189b
Create Date: 2021-12-15 23:36:49.612834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82f9f9506d06'
down_revision = 'ff2e3d7b189b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drinkings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('option', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('profiles', sa.Column('smoking_id', sa.Integer(), nullable=True))
    op.add_column('profiles', sa.Column('drinking_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'profiles', 'smokings', ['smoking_id'], ['id'])
    op.create_foreign_key(None, 'profiles', 'drinkings', ['drinking_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_column('profiles', 'drinking_id')
    op.drop_column('profiles', 'smoking_id')
    op.drop_table('drinkings')
    # ### end Alembic commands ###
