"""empty message

Revision ID: 94272743cbe4
Revises: 0d1d009fb49c
Create Date: 2021-12-15 21:57:41.636032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94272743cbe4'
down_revision = '0d1d009fb49c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('profiles_religion_id_fkey', 'profiles', type_='foreignkey')
    op.drop_constraint('profiles_politic_id_fkey', 'profiles', type_='foreignkey')
    op.drop_column('profiles', 'politic_id')
    op.drop_column('profiles', 'religion_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('religion_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('politic_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('profiles_politic_id_fkey', 'profiles', 'politics', ['politic_id'], ['id'])
    op.create_foreign_key('profiles_religion_id_fkey', 'profiles', 'religions', ['religion_id'], ['id'])
    # ### end Alembic commands ###
