"""empty message

Revision ID: 9505955c60fc
Revises: d4c00dbe0c17
Create Date: 2021-12-27 15:09:29.021386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9505955c60fc'
down_revision = 'd4c00dbe0c17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('likes_match_profile_id_fkey', 'likes', type_='foreignkey')
    op.create_foreign_key(None, 'likes', 'users', ['match_profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.create_foreign_key('likes_match_profile_id_fkey', 'likes', 'profiles', ['match_profile_id'], ['id'])
    # ### end Alembic commands ###
