"""empty message

Revision ID: 9db6c21f49ce
Revises: d4b21fd5b67e
Create Date: 2021-12-12 21:12:22.204097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9db6c21f49ce'
down_revision = 'd4b21fd5b67e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('image_url1', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('image_url2', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('image_url3', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('image_url4', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('image_url5', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('image_url6', sa.String(), nullable=True))
    op.drop_column('profiles', 'image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('profiles', 'image_url6')
    op.drop_column('profiles', 'image_url5')
    op.drop_column('profiles', 'image_url4')
    op.drop_column('profiles', 'image_url3')
    op.drop_column('profiles', 'image_url2')
    op.drop_column('profiles', 'image_url1')
    # ### end Alembic commands ###
