"""empty message

Revision ID: a67797152344
Revises: 70a330ead019
Create Date: 2021-12-15 21:12:19.733114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a67797152344'
down_revision = '70a330ead019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genders', sa.Column('type', sa.String(length=255), nullable=True))
    op.add_column('genders', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('genders', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('genders', 'updated_at')
    op.drop_column('genders', 'created_at')
    op.drop_column('genders', 'type')
    # ### end Alembic commands ###
