"""empty message

Revision ID: b9dd16f28d9f
Revises: 2291a0ff80c4
Create Date: 2021-12-22 14:45:49.704024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9dd16f28d9f'
down_revision = '2291a0ff80c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('markerss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('lat', sa.Numeric(scale=13, asdecimal=False), nullable=True),
    sa.Column('lng', sa.Numeric(scale=13, asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('markerss')
    # ### end Alembic commands ###
