"""empty message

Revision ID: d5ef0f9292b2
Revises: 5516cfe71b18
Create Date: 2021-12-15 21:06:55.176815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5ef0f9292b2'
down_revision = '5516cfe71b18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genders', sa.Column('type', sa.String(length=255), nullable=True))
    op.drop_column('genders', 'preference')
    op.add_column('profiles', sa.Column('gender_preference_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'profiles', 'genders', ['gender_preference_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_column('profiles', 'gender_preference_id')
    op.add_column('genders', sa.Column('preference', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('genders', 'type')
    # ### end Alembic commands ###
