"""empty message

Revision ID: d9b2e3ebc326
Revises: 60d2eea9353f
Create Date: 2021-12-12 21:32:29.573629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9b2e3ebc326'
down_revision = '60d2eea9353f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
