"""empty message

Revision ID: ff2e3d7b189b
Revises: 1a8d22df58ed
Create Date: 2021-12-15 23:30:25.413927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff2e3d7b189b'
down_revision = '1a8d22df58ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smokings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('option', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('profiles', 'smoking')
    op.drop_column('profiles', 'drinking')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('drinking', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('smoking', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_table('smokings')
    # ### end Alembic commands ###
